apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowboys
spec:
  selector:
    matchLabels:
      run: cowboys
  replicas: 6
  template:
    metadata:
      labels:
        run: cowboys
    spec:
      containers:
        - name: cowboys
          imagePullPolicy: Never
          image: cowboy:latest
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000
